language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION='Django>=1.4,<1.5'
  - DJANGO_VERSION='Django>=1.5,<1.6'
  - DJANGO_VERSION='Django>=1.6,<1.7'
  - DJANGO_VERSION='Django>=1.7,<1.8'
  - DJANGO_VERSION='Django>=1.8,<1.9'
  - DJANGO_VERSION='Django>=1.9,<1.10'
  - DJANGO_VERSION='Django>=1.10,<1.11'
  - DJANGO_VERSION='Django>=1.11,<2.0'
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION='Django>=1.7,<1.8'
    - python: "2.6"
      env: DJANGO_VERSION='Django>=1.8,<1.9'
    - python: "2.6"
      env: DJANGO_VERSION='Django>=1.9,<1.10'
    - python: "2.6"
      env: DJANGO_VERSION='Django>=1.10,<1.11'
    - python: "2.6"
      env: DJANGO_VERSION='Django>=1.11,<2.0'
    - python: "2.6"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "2.7"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.5,<1.6'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.9,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.10,<1.11'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.11,<2.0'
    - python: "3.3"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.4"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "3.4"
      env: DJANGO_VERSION='Django>=1.5,<1.6'
    - python: "3.4"
      env: DJANGO_VERSION='Django>=1.6,<1.7'
    - python: "3.4"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.5,<1.6'
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.6,<1.7'
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.7,<1.8'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.5,<1.6'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.6,<1.7'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.7,<1.8'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.8,<1.9'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.9,<1.10'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.10,<1.11'
  allow_failures:
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

install:
  - pip install -q $DJANGO_VERSION
  - pip install tox coveralls flake8

script:
  - coverage erase
  - if [[ $(python -c 'import sys; print("0" if sys.version_info < (2, 7) else "1")') == "1" ]]; then flake8 --ignore=E501; fi
  - PYTHONPATH=. coverage run -p example/run_tests.py
  - PYTHONPATH=. coverage run -p example/run_tests.py example.settings_no_debug
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - goinnn@gmail.com
    - blag@users.noreply.github.com
